import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import Nav from "../../components/HOME/Nav";
import Footer from "../../components/HOME/Footer";
import FirstProvider from "../../components/providers/FirstProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <FirstProvider>
           {children}
        </FirstProvider>
      </body>
    </html>
  );
}
